name: Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Create kube-config and install Helm
        run: |
          aws eks --region ap-northeast-2 update-kubeconfig --name fastcampus-infra-cluster
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install Helm chart
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        run: |
          helm upgrade --install fc-incident-scenarios chart \
            -f helm-prod-values.yaml \
            --set workload.image.tag="$(git rev-parse --short HEAD)" \
            --set secret.body.DATABASE_NAME="$(echo -n $DATABASE_NAME | base64)" \
            --set secret.body.DATABASE_USER="$(echo -n $DATABASE_USER | base64)" \
            --set secret.body.DATABASE_PASSWORD="$(echo -n $DATABASE_PASSWORD | base64)" \
            --set secret.body.DATABASE_HOST="$(echo -n $DATABASE_HOST | base64)" \
            --set common.awsAccount="$(aws sts get-caller-identity --query Account --output text)"